name: buid u-boot pinecube

on:
  push:
    branches: [ audio-codec ]
  pull_request:
    branches: [ audio-codec ]

env:
  REPO_URL: https://github.com/juanesf/u-boot
  REPO_BRANCH: audio-codec
  TZ: America/Santiago

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        rm -Rf ~/u-boot
        sudo -E apt-get update && sudo apt-get install -y bison flex python3-dev swig flex git
        sudo -E apt-get install -y gcc-arm-linux-gnueabihf make
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        git clone $REPO_URL -b $REPO_BRANCH ~/u-boot

    - name: change folder
      run: cd ~/u-boot

    - name: configure pinecube defconfig
      run: make CROSS_COMPILE=arm-linux-gnueabihf- pinecube_defconfig

    - name: make u-boot
      run: make CROSS_COMPILE=arm-linux-gnueabihf- -j$(nproc)

    - name: Upload binary u-boot
      uses: actions/upload-artifact@v2
      with:
        name: u-boot-sunxi-with-spl.bin
        path: /home/runner/work/u-boot/u-boot/u-boot-sunxi-with-spl.bin

    - name: Upload dtb u-boot
      uses: actions/upload-artifact@v2
      with:
        name: sun8i-s3-pinecube.dtb
        path: /home/runner/work/u-boot/u-boot/arch/arm/dts/sun8i-s3-pinecube.dtb

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
